name: Java CI with Maven on Mac OS

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests from'
        required: false
        default: 'main'
      browser:
        description: 'browser to run tests'
        required: true
        type: choice
        options:
          - chrome
          - firefox
          - safari
          - edge
      platform:
        description:  'platform to run tests'
        required: true
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

jobs:
  build:

    runs-on: ${{ github.event.inputs.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean verify serenity:aggregate -Dwebdriver.driver=${{ github.event.inputs.browser }}

