name: Regression Tests Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run tests from'
        required: false
        default: 'main'
      browser:
        description: 'browser to run tests'
        required: true
        type: choice
        options:
          - chrome
          - firefox
          - safari
          - edge
      os:
        description:  'environment to run tests'
        required: true
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

jobs:
  build:

    runs-on: ${{github.event.inputs.os}}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Edge
        if: ${{github.event.inputs.browser}} = 'edge'
        uses: browser-actions/setup-edge@latest
        with:
            edge-version: beta

      - name: Setup Chrome
        if: ${{github.event.inputs.browser}} = 'chrome'
        uses: browser-actions/setup-chrome@latest
        with:
            chrome-version: latest

      - name: Setup Safari
        if: ${{github.event.inputs.browser}} = 'safari'
        uses: browser-actions/setup-safari@latest
        with:
            safari-version: latest

      - name: Setup Firefox
        if: ${{github.event.inputs.browser}} = 'firefox'
        uses: browser-actions/setup-firefox@latest
        with:
            firefox-version: latest

      - name: Run Regression Tests
        run: mvn clean verify serenity:aggregate -Dwebdriver.driver=${{github.event.inputs.browser}}
        
      - name: Upload Serenity Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
           name: Serenity Report
           path: target/site/serenity
